services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres       # if not specified default postgres
      POSTGRES_DB: hello_dev        # if not specified, equal to POSTGRES_USER
      POSTGRES_PASSWORD: postgres   # if not specified default postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/18/docker
    networks:
      - hello_dev

  pgadmin:
    image: dockage/phppgadmin
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=hello_dev
    ports:
      - 8080:80
    networks:
      - hello_dev

networks:
  hello_dev:


volumes:
  postgresql-data: